version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=REPLACE_WITH_ACTUAL_USER
      - POSTGRES_PASSWORD=REPLACE_WITH_ACTUAL_PASSWORD
      - POSTGRES_DB=first

volumes:
  postgres-data:
    driver: local